/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.*;
import javax.swing.*;
import java.util.ArrayList;
/**
 *
 * @author Hashim Ali Khan
 */
//class for setting the quiz and creating question in it
public class settingQuiz extends JFrame{
    public static int count=1;
    private static int mcq=0;
    private static int tf=0;
     //arrays holding different objects
    public ArrayList<String> qd=new ArrayList<>();
    public ArrayList<JTextField> al=new ArrayList<>();
    public ArrayList<JTextField> options=new ArrayList<>();
    public ArrayList<JRadioButton> cans=new ArrayList<>();
    public ArrayList<String> type=new ArrayList<>();      
    public ArrayList<data> obj=new ArrayList<>();
    /**
     * Creates new form settingQuiz
     */
    public settingQuiz() {
        initComponents();
        jLabel3.setText("0");
        jLabel5.setText("0");
        jLabel7.setText("0");
    }
        
        
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        newQuiz = new javax.swing.JButton();
        check = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(2200, 1826));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 2297));

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 2400));

        label1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        label1.setText("Add a new Question:");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MCQ", "True/False" }));

        jLabel1.setText("Type:");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        label2.setText("Creating a new Quiz");

        jLabel2.setText("Added Questions:");

        jLabel4.setText("MCQ's:");

        jLabel5.setText("   ");

        jLabel6.setText("True/False:");

        jLabel10.setText("Description:");

        jLabel12.setText("Title:");

        title.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                titleComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(790, 790, 790)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(97, 97, 97)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(229, 229, 229))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addComponent(jButton1)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))))
                    .addComponent(jLabel12))
                .addGap(17, 17, 17))
        );

        jScrollPane1.setViewportView(jPanel1);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        newQuiz.setText("New Quiz");
        newQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQuizActionPerformed(evt);
            }
        });

        Logout.setText("Log out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(save)
                        .addGap(35, 35, 35)
                        .addComponent(newQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Logout)))
                .addGap(0, 1010, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newQuiz)
                        .addComponent(Logout)
                        .addComponent(save)))
                .addGap(0, 669, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //creating mcq's and true false dynamically
        jLabel3.setText(""+count); 
         String val=jComboBox1.getSelectedItem().toString();
         JLabel lab=new JLabel("Q."+count);
         lab.setBounds(10, 63+count*200, 30, 25);
         JTextField q=new JTextField();
         q.setText("q"+count);
         q.setBounds(60, 65+count*200, 600, 25); //setting position on 
         jPanel1.add(lab); //adding panel for display
         jPanel1.add(q);
         al.add(q); 
         type.add(val);
        switch (val) {
            case "MCQ":
                {
                    mcq++;
                    jLabel5.setText(""+mcq);
                    JRadioButton w =new JRadioButton();
                    JRadioButton x =new JRadioButton();
                    JRadioButton y =new JRadioButton();
                    JRadioButton z =new JRadioButton();
                    w.setName("btna");
                    x.setName("btnb");
                    y.setName("btnc");
                    z.setName("btnd");
                    w.setBounds(30,110+count*200,20,17);
                    x.setBounds(30,140+count*200,20,17);
                    y.setBounds(30,170+count*200,20,17);
                    z.setBounds(30,200+count*200,20,17);
                    ButtonGroup ans=new ButtonGroup();
                    ans.add(w);
                    ans.add(x);
                    ans.add(y);
                    ans.add(z);
                    cans.add(w);
                    cans.add(x);
                    cans.add(y);
                    cans.add(z);
                    jPanel1.add(w);
                    jPanel1.add(x);
                    jPanel1.add(y);
                    jPanel1.add(z);
                    JLabel opt1=new JLabel("A)");
                    JLabel opt2=new JLabel("B)");
                    JLabel opt3=new JLabel("C)");
                    JLabel opt4=new JLabel("D)");
                    opt1.setBounds(60,108+count*200,20,20);
                    opt2.setBounds(60,140+count*200,20,20);
                    opt3.setBounds(60,170+count*200,20,20);
                    opt4.setBounds(60,200+count*200,20,20);
                    jPanel1.add(opt1);
                    jPanel1.add(opt2);
                    jPanel1.add(opt3);
                    jPanel1.add(opt4);
                    JTextField A =new JTextField();
                    JTextField B =new JTextField();
                    JTextField C =new JTextField();
                    JTextField D =new JTextField();
                    A.setText("A"+count);
                    B.setText("B"+count);
                    C.setText("C"+count);
                    D.setText("D"+count);
                    A.setBounds(90, 110+count*200, 200, 25);
                    B.setBounds(90, 140+count*200, 200, 25);
                    C.setBounds(90, 170+count*200, 200, 25);
                    D.setBounds(90, 200+count*200, 200, 25);
                    jPanel1.add(A);
                    jPanel1.add(B);
                    jPanel1.add(C);
                    jPanel1.add(D);
                    options.add(A);
                    options.add(B);
                    options.add(C);
                    options.add(D);
                    break;
                }
            case "True/False":
                {
                    tf++;
                    jLabel7.setText(""+tf);
                    JRadioButton A =new JRadioButton("True");
                    JRadioButton B =new JRadioButton("False");
                    A.setName("A"+count);
                    B.setName("B"+count);
                    ButtonGroup BG=new ButtonGroup();
                    BG.add(A);
                    BG.add(B);
                    A.setBounds(60, 110+count*200, 100, 25);
                    B.setBounds(60, 140+count*200, 100, 25);
                    jPanel1.add(A);
                    jPanel1.add(B);
                    cans.add(A);
                    cans.add(B);
                    break;
                }
        }
         count++;
         revalidate();
         repaint();    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
           // TODO add your handling code here:
         
          int x=0;
          data d=new data();
          d.dtitle=qd.get(0);
          d.ddescription=qd.get(1);
          obj.add(d);
          for(int i=1;i<count;i++){
          data store=new data();
          store.qno=i;
          store.ques=al.get(i-1).getText();
          store.qtype=type.get(i-1);
          if(store.qtype.equals("MCQ")){          
          store.optA=options.get(x*4).getText();
          store.optB=options.get((x*4)+1).getText();
          store.optC=options.get((x*4)+2).getText();
          store.optD=options.get((x*4)+3).getText();
          store.r1=cans.get(x*4).isSelected();
          store.r2=cans.get((x*4)+1).isSelected();
          store.r3=cans.get((x*4)+2).isSelected();
          store.r4=cans.get((x*4)+3).isSelected();
          x++;
          }
          else if(store.qtype.equals("True/False")){
          store.r1=cans.get(x*4).isSelected();
          store.r2=cans.get((x*4)+1).isSelected();
          }
          obj.add(store);
          }
         serialize(obj);
    }//GEN-LAST:event_saveActionPerformed
public void serialize(ArrayList<data> st){
try {
         FileOutputStream fileOut =
         new FileOutputStream("quizer.ser",true);
         ObjectOutputStream out = new ObjectOutputStream(fileOut);
         out.writeObject(st);
         out.close();
         fileOut.close();
         System.out.printf("Serialized array is saved in quizer.ser");
      }catch(IOException i) {
         i.printStackTrace();
      }

}
public void quiz_description(){
           title.setText(qd.get(0));
           description.setText(qd.get(1));
           jPanel1.add(title);   
}


    private void newQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQuizActionPerformed
        // TODO add your handling code here:
        createQuiz cq=new createQuiz();
        cq.setVisible(true);
        dispose();
    }//GEN-LAST:event_newQuizActionPerformed

    private void titleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_titleComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_titleComponentShown

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new settingQuiz().setVisible(true);
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JLabel check;
    private javax.swing.JLabel description;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton newQuiz;
    private javax.swing.JButton save;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static class JtextField {

        public JtextField() {
        }
    }
}

